spring.application.name=medicube

spring.datasource.url=jdbc:mysql://localhost:3306/medicubedb
spring.datasource.username=root
spring.datasource.password=Navya$ri@9717

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin123


server.error.include-message=always
server.error.include-binding-errors=always
